PGI Bug nvlink __pgi_ldg_unknown
There was an error in the last two commits. I forgot to add prim_advection_openacc_mod.F90.

This commit contains a link-time error for PGI with the error:

nvlink error   : Undefined reference to '__pgi_ldg_unknown' in 'CMakeFiles/preqx.dir/__/share/prim_advection_openacc_mod.F90.o'